// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj6SyZ67bR4hpRGVREZabsxN6pjm8KBjs',
    appId: '1:402676696580:web:2ebeedc6373a8ddf16d751',
    messagingSenderId: '402676696580',
    projectId: 'mahmoud-store-b7e94',
    authDomain: 'mahmoud-store-b7e94.firebaseapp.com',
    storageBucket: 'mahmoud-store-b7e94.firebasestorage.app',
    measurementId: 'G-EMHBREF7T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwf2evL1nPpuYOdwoFC_EOPeW2DhoC2zs',
    appId: '1:402676696580:android:234e1436517f381716d751',
    messagingSenderId: '402676696580',
    projectId: 'mahmoud-store-b7e94',
    storageBucket: 'mahmoud-store-b7e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEjRpAjQmwwBS8XKj_0FLnL8GDYxJC9R0',
    appId: '1:402676696580:ios:1dec6e11ee1ba5ff16d751',
    messagingSenderId: '402676696580',
    projectId: 'mahmoud-store-b7e94',
    storageBucket: 'mahmoud-store-b7e94.firebasestorage.app',
    iosBundleId: 'com.example.mahmoudStore',
  );

}